---
# Install Helm on the control plane node
- name: Install Helm on monitoring_nodes
  hosts: monitoring_nodes
  become: true
  vars:
    helm_version: "3.13.3"
    
  tasks:
    - name: Ensure python3-pip is installed (required to install kubernetes client)
      apt:
        name: python3-pip
        state: present
        update_cache: yes
      when: ansible_facts['pkg_mgr'] == 'apt' or ansible_pkg_mgr is defined and ansible_pkg_mgr == 'apt'

    - name: Install kubernetes Python library for Ansible k8s module
      pip:
        name: kubernetes
        state: present
        executable: pip3
      become: true
      when: ansible_facts is defined and ansible_facts['python'] is defined

    - name: Download Helm installer script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0755'

    - name: Install Helm
      shell: /tmp/get_helm.sh
      environment:
        HELM_INSTALL_DIR: /usr/local/bin

    - name: Verify Helm installation
      command: helm version --short
      register: helm_version_output

    - name: Display Helm version
      debug:
        msg: "Installed Helm version: {{ helm_version_output.stdout }}"

    - name: Add common Helm repositories
      kubernetes.core.helm_repository:
        name: "{{ item.name }}"
        repo_url: "{{ item.url }}"
      loop:
        - name: prometheus-community
          url: https://prometheus-community.github.io/helm-charts
        - name: grafana
          url: https://grafana.github.io/helm-charts
        - name: jetstack
          url: https://charts.jetstack.io
        - name: stable
          url: https://charts.helm.sh/stable

    - name: Update Helm repositories
      command: helm repo update

    - name: Create monitoring namespace
      kubernetes.core.k8s:
        name: monitoring
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: /root/.kube/config