---
# Install Helm on the control plane node
- name: Install Helm on monitoring_nodes
  hosts: monitoring_nodes
  become: true
  vars:
    helm_version: "3.13.3"
    
  tasks:
    - name: Ensure kubernetes Python package is available (Debian package preferred)
      apt:
        name: python3-kubernetes
        state: present
        update_cache: yes
      when: ansible_facts['pkg_mgr'] == 'apt' or ansible_pkg_mgr is defined and ansible_pkg_mgr == 'apt'

    - name: Fallback - install kubernetes Python library via pip if apt package missing
      pip:
        name: kubernetes
        state: present
        executable: pip3
      become: true
      when: ansible_facts['pkg_mgr'] is not defined or ansible_facts['pkg_mgr'] != 'apt'

    - name: Download Helm installer script (primary attempt)
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0755'
        validate_certs: false
        timeout: 30
      register: helm_download
      ignore_errors: true

    - name: Download Helm installer script (curl fallback)
      ansible.builtin.shell: |
        curl -fsSL -o /tmp/get_helm.sh \
          https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 0755 /tmp/get_helm.sh
      args:
        creates: /tmp/get_helm.sh
      when: helm_download is failed or 'cert_file' in (helm_download.msg | default('')) or 'urllib3' in (helm_download.msg | default(''))

    - name: Verify Helm script downloaded
      ansible.builtin.stat:
        path: /tmp/get_helm.sh
      register: helm_script

    - name: Fail if Helm download failed
      ansible.builtin.fail:
        msg: "Failed to download Helm installer script. Check network connectivity."
      when: not helm_script.stat.exists

    - name: Install Helm
      shell: /tmp/get_helm.sh
      environment:
        HELM_INSTALL_DIR: /usr/local/bin

    - name: Verify Helm installation
      command: helm version --client
      register: helm_version_output

    - name: Display Helm version
      debug:
        msg: "Installed Helm version: {{ helm_version_output.stdout }}"

    - name: Add common Helm repositories
      kubernetes.core.helm_repository:
        name: "{{ item.name }}"
        repo_url: "{{ item.url }}"
      loop:
        - name: prometheus-community
          url: https://prometheus-community.github.io/helm-charts
        - name: grafana
          url: https://grafana.github.io/helm-charts
        - name: jetstack
          url: https://charts.jetstack.io
        - name: stable
          url: https://charts.helm.sh/stable

    - name: Update Helm repositories
      command: helm repo update

    - name: Create monitoring namespace
      kubernetes.core.k8s:
        name: monitoring
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: /root/.kube/config