# Example: Minimal Jellyfin Deployment Configuration
# Copy this to ansible/group_vars/all.yml for minimal deployment

# === Infrastructure Mode ===
infrastructure_mode: kubernetes

# === Kubernetes Configuration ===
kubernetes_version: "1.29"

# === Jellyfin Storage Configuration ===
# MINIMAL DEPLOYMENT: Use direct hostPath volumes (recommended for simple setups)
jellyfin_use_persistent_volumes: false

# Media directory path on storage node
jellyfin_media_path: /srv/media

# Config directory path on storage node  
jellyfin_config_path: /var/lib/jellyfin

# Skip mount verification (set to true to bypass pre-deployment checks)
jellyfin_skip_mount_verification: true

# === Alternative: Advanced Deployment with Persistent Volumes ===
# Uncomment these settings if you prefer PV/PVC management:
# jellyfin_use_persistent_volumes: true
# jellyfin_skip_mount_verification: false

# === Other Required Settings ===
# Add your other configuration as needed...