---
# Fix Jellyfin probe configuration
# This patch updates the pod to use the correct health check endpoint
apiVersion: v1
kind: Pod
metadata:
  name: jellyfin
  namespace: jellyfin
  labels:
    app: jellyfin
    component: media-server
spec:
  nodeSelector:
    kubernetes.io/hostname: storagenodet3500
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  containers:
  - name: jellyfin
    image: jellyfin/jellyfin:latest
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 8096
      protocol: TCP
    - name: https
      containerPort: 8920
      protocol: TCP
    - name: dlna
      containerPort: 1900
      protocol: UDP
    - name: discovery
      containerPort: 7359
      protocol: UDP
    env:
    - name: JELLYFIN_PublishedServerUrl
      value: "http://192.168.4.61:30096"
    - name: JELLYFIN_HTTP_BIND_ADDRESS
      value: "0.0.0.0"
    - name: JELLYFIN_HTTP_PORT
      value: "8096"
    # Health check configuration
    - name: HEALTHCHECK_URL
      value: "http://localhost:8096/health"
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "2"
    volumeMounts:
    - name: jellyfin-config
      mountPath: /config
    - name: jellyfin-cache
      mountPath: /cache
    - name: jellyfin-media
      mountPath: /media
      readOnly: true
    # Fixed probe configuration - using proper /health endpoint
    livenessProbe:
      httpGet:
        path: /health
        port: 8096
        scheme: HTTP
      initialDelaySeconds: 180
      periodSeconds: 60
      timeoutSeconds: 30
      failureThreshold: 5
    readinessProbe:
      httpGet:
        path: /health
        port: 8096
        scheme: HTTP
      initialDelaySeconds: 120
      periodSeconds: 30
      timeoutSeconds: 15
      failureThreshold: 5
    startupProbe:
      httpGet:
        path: /health
        port: 8096
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 15
      timeoutSeconds: 10
      failureThreshold: 30
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      capabilities:
        drop:
        - ALL
  volumes:
  - name: jellyfin-config
    hostPath:
      path: /var/lib/jellyfin
      type: DirectoryOrCreate
  - name: jellyfin-cache
    emptyDir:
      sizeLimit: 10Gi
  - name: jellyfin-media
    hostPath:
      path: /srv/media
      type: DirectoryOrCreate
  restartPolicy: Always