---
- name: restart kubelet
  become: true
  ansible.builtin.service:
    name: kubelet
    state: restarted
    enabled: true

- name: restart NetworkManager
  become: true
  ansible.builtin.service:
    name: NetworkManager
    state: restarted
  ignore_errors: true
