- name: Debug become password variable
  debug:
    msg: "{{ inventory_hostname }}: ansible_become_pass is {{ ansible_become_pass | default('NOT SET') }}"

- name: Ensure /etc/hosts has all cluster nodes
  become: true
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      # VMStation Kubernetes Cluster Nodes
      192.168.4.63 masternode
      192.168.4.61 storagenodet3500
      192.168.4.62 homelab
    marker: "# {mark} ANSIBLE MANAGED BLOCK - VMStation Cluster"
    create: yes
    backup: no

- name: Check kubectl version
  ansible.builtin.command:
    cmd: kubectl version --client
  register: kubectl_version
  ignore_errors: true
- name: Check kubelet version
  become: true
  ansible.builtin.command:
    cmd: kubelet --version
  register: kubelet_version
  ignore_errors: true

- name: Gather package manager info (apt)
  become: true
  ansible.builtin.shell: |
    if command -v apt >/dev/null 2>&1; then echo apt; elif command -v dnf >/dev/null 2>&1; then echo dnf; fi
  register: pkg_mgr
  changed_when: false

- name: Warn about version skew between client and server if known
  ansible.builtin.debug:
    msg: |
      kubectl: {{ kubectl_version.stdout | default('unknown') }}
      kubelet: {{ kubelet_version.stdout | default('unknown') }}
  when: kubectl_version is defined
