---
# Main Kubernetes deployment playbook for VMStation
# This replaces the Podman-based infrastructure with Kubernetes

# Prerequisite: Ensure monitoring directories and permissions are set up
- name: Ensure monitoring prerequisites
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Ensure monitoring directories exist with proper permissions
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: root
        group: root
      loop:
        - /srv/monitoring_data
        - /srv/monitoring_data/grafana
        - /srv/monitoring_data/prometheus
        - /srv/monitoring_data/loki
        - /srv/monitoring_data/promtail
        - /srv/monitoring_data/local-path-provisioner
      tags: [prerequisites]

- import_playbook: kubernetes/rhel10_setup_fixes.yaml
- import_playbook: kubernetes/setup_cluster.yaml
- import_playbook: kubernetes/setup_helm.yaml  
- import_playbook: kubernetes/setup_cert_manager.yaml
- import_playbook: kubernetes/setup_local_path_provisioner.yaml
- import_playbook: kubernetes/deploy_monitoring.yaml
# Jellyfin HA removed. Add your minimal jellyfin deployment manually if needed.