- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../group_vars/secrets.yml
  tasks:
    - name: Check Kubernetes API connectivity (quick)
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Namespace
        name: kube-system
      register: k8s_api_check
      failed_when: false
      changed_when: false

    - name: Fail early with helpful message if Kubernetes API unreachable
      ansible.builtin.fail:
        msg: |
          Kubernetes API appears unreachable or timed out. This play creates cluster resources (namespace and secrets) and requires a functioning API server.
          Check cluster connectivity and kubeconfig before retrying.
      when: k8s_api_check is not defined or (k8s_api_check is defined and k8s_api_check.failed)

    - name: Ensure drone namespace exists
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: drone

    - name: Create drone secrets from group_vars
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: drone-secrets
            namespace: drone
          type: Opaque
          stringData:
            rpc-secret: "{{ drone_rpc_secret | default('changeme') }}"
            github-client-id: "{{ drone_github_client_id | default('') }}"
            github-client-secret: "{{ drone_github_client_secret | default('') }}"
            server-host: "{{ drone_server_host | default('') }}"