- name: Create and bind Drone CI ServiceAccount
  hosts: master
  become: yes
  tasks:
    - name: Apply Drone RBAC manifest
      shell: kubectl apply -f /root/ansible/k8s/drone-rbac.yaml
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml