- name: Cleanup K3s Agent from Worker Node
  hosts: worker
  become: yes
  tasks:
    - name: Stop K3s agent if running
      systemd:
        name: k3s-agent
        state: stopped
      ignore_errors: yes

    - name: Remove K3s completely
      shell: |
        sudo /usr/local/bin/k3s-agent-uninstall.sh || true
        sudo rm -rf /etc/rancher/k3s
        sudo rm -rf /var/lib/rancher/k3s
        sudo rm -rf /usr/local/bin/k3s
        sudo rm -rf /etc/systemd/system/k3s-agent.service
        sudo systemctl daemon-reload