- name: Deploy K3s Worker Node with Custom Hostname
  hosts: worker
  become: yes
  vars:
    node_name: worker
  tasks:
    - name: Set hostname to "{{ node_name }}"
      hostname:
        name: "{{ node_name }}"

    # Copy TLS Certificates to Worker
    - name: Create TLS directory
      file:
        path: /etc/rancher/k3s/server/tls
        state: directory
        mode: "0700"

    - name: Copy TLS certificates from master to worker
      copy:
        src: /etc/rancher/k3s/server/tls/
        dest: /etc/rancher/k3s/server/tls/
        owner: root
        group: root
        mode: "0600"
        remote_src: yes

    # Install K3s Worker with Correct Credentials
    - name: Install K3s Worker
      shell: |
        curl -sfL https://get.k3s.io | \
        K3S_URL="{{ master_socket }}" \
        K3S_TOKEN="{{ k3s_token }}" \
        K3S_CERTIFICATE_AUTHORITY="/etc/rancher/k3s/server/tls/server-ca.crt" \
        sh -

    - name: Restart K3s agent
      systemd:
        name: k3s-agent
        state: restarted

    # Deploy your app as a pod (example manifest)
    - name: Copy app deployment manifest to worker
      copy:
        src: ../k8s/deployment.yaml
        dest: /tmp/deployment.yaml

    - name: Apply app deployment manifest
      shell: |
        KUBECONFIG=/etc/rancher/k3s/k3s.yaml kubectl apply -f /tmp/deployment.yaml
      args:
        executable: /bin/bash
