---
 - name: Ensure Drone hostPath marker file exists
   hosts: all
   become: true
   gather_facts: false
   vars:
     drone_hostpath: /mnt/storage/drone
     marker_file: "{{ drone_hostpath }}/.drone_ready"
     marker_content: |
       Created by Ansible to mark drone hostPath presence
       Timestamp: {{ lookup('pipe','date -u +"%Y-%m-%dT%H:%M:%SZ"') }}
     marker_owner_uid: 1000
     marker_owner_gid: 1000
     marker_mode: '0640'

   tasks:
   - name: Create hostPath directory if missing
     file:
       path: "{{ drone_hostpath }}"
       state: directory
       mode: '0750'

   - name: Create marker file with correct owner and content
     copy:
       dest: "{{ marker_file }}"
       content: "{{ marker_content }}\n"
       owner: "{{ marker_owner_uid }}"
       group: "{{ marker_owner_gid }}"
       mode: "{{ marker_mode }}"
       force: yes

   - name: Ensure ownership of entire hostPath is correct for Drone
     file:
       path: "{{ drone_hostpath }}"
       recurse: yes
       owner: "{{ marker_owner_uid }}"
       group: "{{ marker_owner_gid }}"
       mode: '0750'