- name: Deploy Monitoring Stack and Drone with Helm
  hosts: master
  become: yes
  tasks:
    - name: Add Prometheus Community repo
      shell: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      args:
        creates: /root/.cache/helm/repository/prometheus-community-index.yaml

    - name: Add Drone repo
      shell: helm repo add drone https://charts.drone.io
      args:
        creates: /root/.cache/helm/repository/drone-index.yaml

    - name: Update Helm repos
      shell: helm repo update

    - name: Install kube-prometheus-stack
      community.kubernetes.helm:
        name: kube-prometheus-stack
        chart_ref: prometheus-community/kube-prometheus-stack
        release_namespace: monitoring
        create_namespace: true
        values:
          grafana:
            adminPassword: "{{ grafana_admin_pass }}"
            service:
              type: NodePort
            additionalDataSources:
              - name: Prometheus
                type: prometheus
                url: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
                access: proxy
                isDefault: true
            dashboards:
              default:
                k8s-cluster:
                  gnetId: 315
                  revision: 4
                  datasource: Prometheus
          prometheus:
            service:
              type: NodePort
            prometheusSpec:
              maximumStartupDurationSeconds: 300
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Print Prometheus NodePort
      shell: |
        kubectl -n monitoring get svc kube-prometheus-stack-prometheus -o jsonpath="{.spec.ports[0].nodePort}"
      register: prometheus_nodeport
      changed_when: false

    - name: Show Prometheus NodePort
      debug:
        msg: "Prometheus is available at http://{{ ansible_host }}:{{ prometheus_nodeport.stdout }}"

    - name: Print Grafana NodePort
      shell: |
        kubectl -n monitoring get svc kube-prometheus-stack-grafana -o jsonpath="{.spec.ports[0].nodePort}"
      register: grafana_nodeport
      changed_when: false

    - name: Show Grafana NodePort
      debug:
        msg: "Grafana is available at http://{{ ansible_host }}:{{ grafana_nodeport.stdout }}"

    - name: Install Drone
      community.kubernetes.helm:
        name: drone
        chart_ref: drone/drone
        release_namespace: drone
        create_namespace: true
        values:
          env:
            DRONE_SERVER_HOST: "{{ drone_server_host }}"
            DRONE_SERVER_PROTO: "{{ drone_server_proto }}"
            DRONE_RPC_SECRET: "{{ drone_rpc_secret }}"
            DRONE_GITHUB_CLIENT_ID: "{{ drone_github_client_id }}"
            DRONE_GITHUB_CLIENT_SECRET: "{{ drone_github_client_secret }}"
            DRONE_GITHUB_SERVER: "{{ drone_github_server }}"
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml