- name: Deploy Monitoring Stack and Drone with Helm
  hosts: master
  become: yes
  tasks:

    - name: Uninstall Prometheus stack if present
      shell: helm uninstall kube-prometheus-stack -n monitoring || true
      ignore_errors: yes

    - name: Uninstall Loki if present
      shell: helm uninstall loki -n monitoring || true
      ignore_errors: yes

    - name: Uninstall Promtail if present
      shell: helm uninstall promtail -n monitoring || true
      ignore_errors: yes

    - name: Uninstall Drone if present
      shell: helm uninstall drone -n drone || true
      ignore_errors: yes

    # ...rest of your install tasks...

    - name: Add Prometheus Community repo
      shell: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      args:
        creates: /root/.cache/helm/repository/prometheus-community-index.yaml

    - name: Add Drone repo
      shell: helm repo add drone https://charts.drone.io
      args:
        creates: /root/.cache/helm/repository/drone-index.yaml

    - name: Add Grafana Loki repo
      shell: helm repo add grafana https://grafana.github.io/helm-charts
      args:
        creates: /root/.cache/helm/repository/grafana-index.yaml

    - name: Update Helm repos
      shell: helm repo update

    - name: Install kube-prometheus-stack
      community.kubernetes.helm:
        name: kube-prometheus-stack
        chart_ref: prometheus-community/kube-prometheus-stack
        release_namespace: monitoring
        create_namespace: true
        values:
          grafana:
            adminPassword: "{{ grafana_admin_pass }}"
            service:
              type: NodePort
            # additionalDataSources:
            #   - name: Prometheus
            #     type: prometheus
            #     url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
            #     access: proxy
            #     isDefault: true
            #   - name: Loki
            #     type: loki
            #     url: http://loki.monitoring.svc.cluster.local:3100
            #     access: proxy
            # dashboards:
            #   default:
            #     k8s-cluster:
            #       gnetId: 315
            #       revision: 4
            #       datasource: Prometheus
          prometheus:
            service:
              type: NodePort
            prometheusSpec:
              maximumStartupDurationSeconds: 300
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Print Prometheus NodePort
      shell: |
        kubectl -n monitoring get svc kube-prometheus-stack-prometheus -o jsonpath="{.spec.ports[0].nodePort}"
      register: prometheus_nodeport
      changed_when: false

    - name: Show Prometheus NodePort
      debug:
        msg: "Prometheus is available at http://{{ ansible_host }}:{{ prometheus_nodeport.stdout }}"

    - name: Print Grafana NodePort
      shell: |
        kubectl -n monitoring get svc kube-prometheus-stack-grafana -o jsonpath="{.spec.ports[0].nodePort}"
      register: grafana_nodeport
      changed_when: false

    - name: Show Grafana NodePort
      debug:
        msg: "Grafana is available at http://{{ ansible_host }}:{{ grafana_nodeport.stdout }}"

    - name: Install Drone
      community.kubernetes.helm:
        name: drone
        chart_ref: drone/drone
        release_namespace: drone
        create_namespace: true
        values:
          env:
            DRONE_SERVER_HOST: "{{ drone_server_host }}"
            DRONE_SERVER_PROTO: "{{ drone_server_proto }}"
            DRONE_RPC_SECRET: "{{ drone_rpc_secret }}"
            DRONE_GITHUB_CLIENT_ID: "{{ drone_github_client_id }}"
            DRONE_GITHUB_CLIENT_SECRET: "{{ drone_github_client_secret }}"
            DRONE_GITHUB_SERVER: "{{ drone_github_server }}"
          service:
            type: NodePort
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Install Loki
      community.kubernetes.helm:
        name: loki
        chart_ref: grafana/loki
        chart_version: "5.41.4"
        release_namespace: monitoring
        create_namespace: true
        values:
          deploymentMode: SingleBinary
          loki:
            auth_enabled: false
            commonConfig:
              replication_factor: 1
            storage:
              type: filesystem
          singleBinary:
            replicas: 1
            persistence:
              enabled: true
              storageClass: local-path
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Install Promtail
      community.kubernetes.helm:
        name: promtail
        chart_ref: grafana/promtail
        release_namespace: monitoring
        create_namespace: true
        values:
          loki:
            serviceName: loki
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml