- name: Install and configure Helm on master node
  hosts: master
  become: yes
  tasks:
    - name: Download Helm install script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0755'

    - name: Run Helm install script
      shell: /tmp/get_helm.sh

    - name: Ensure Helm is in PATH
      shell: |
        export PATH=$PATH:/usr/local/bin
      args:
        executable: /bin/bash

    # Example: Add stable repo (optional)
    - name: Add Helm stable repo
      shell: helm repo add stable https://charts.helm.sh/stable
      args:
        creates: /root/.cache/helm/repository/stable-index.yaml

    # Example: Update repos (optional)
    - name: Update Helm repos
      shell: helm repo update

    # Example: Deploy a chart (optional)
    # - name: Install nginx-ingress via Helm
    #   community.kubernetes.helm:
    #     name: nginx-ingress
    #     chart_ref: stable/nginx-ingress
    #     release_namespace: kube-system