---
# Main Kubernetes deployment playbook for VMStation
# This replaces the Podman-based infrastructure with Kubernetes
- import_playbook: kubernetes/rhel10_setup_fixes.yaml
- import_playbook: kubernetes/setup_cluster.yaml
- import_playbook: kubernetes/setup_helm.yaml  
- import_playbook: kubernetes/setup_cert_manager.yaml
- import_playbook: kubernetes/deploy_monitoring.yaml
# Jellyfin HA removed. Add your minimal jellyfin deployment manually if needed.