---
# Safe Loki upgrade playbook
# - Compares live StatefulSet with helm-rendered manifest and detects immutable-field changes
# - If immutable changes are present, it can delete only the StatefulSet (PVCs preserved)
#   and re-run `helm upgrade`. This is gated by `auto_approve` (default: false).
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    release: loki-stack
    namespace: monitoring
    values_file: "/tmp/loki-values.yaml"   # set to the values file you want to use (or pass via -e)
    auto_approve: false                     # set to true to allow automatic delete+upgrade
    immutable_indicators:
      - "volumeClaimTemplates"
      - "serviceName"
      - "selector:"
      - "matchLabels"
      - "persistentVolumeClaim"

  tasks:
    - name: Check for required binaries: helm and kubectl
      ansible.builtin.command:
        cmd: "command -v {{ item }}"
      loop:
        - helm
        - kubectl
      register: bin_check
      failed_when: false
      changed_when: false

    - name: Fail if helm or kubectl missing with remediation
      ansible.builtin.fail:
        msg: |
          Required binary '{{ item.item }}' not found in PATH. Install it on the masternode and re-run.

          Example (Debian/Ubuntu):
            sudo apt-get update; sudo apt-get install -y helm kubectl

          Example (RHEL/CentOS):
            sudo dnf install -y helm kubectl
      loop: "{{ bin_check.results }}"
      when: item.rc != 0

    - name: Render desired chart to temporary file
      ansible.builtin.command:
        cmd: "helm template {{ release }} grafana/loki-stack -f {{ values_file }} --namespace {{ namespace }}"
      register: helm_render
      failed_when: false
      changed_when: false

    - name: Save rendered chart to file for diff
      ansible.builtin.copy:
        content: "{{ helm_render.stdout }}"
        dest: "/tmp/desired-{{ release }}.yaml"
      when: helm_render.stdout is defined

    - name: Dump current StatefulSet to file (if exists)
      ansible.builtin.command:
        cmd: "kubectl -n {{ namespace }} get statefulset {{ release }} -o yaml"
      register: current_sts
      failed_when: false
      changed_when: false

    - name: Save current StatefulSet to file when present
      ansible.builtin.copy:
        content: "{{ current_sts.stdout }}"
        dest: "/tmp/current-{{ release }}.yaml"
      when: current_sts.stdout is defined and current_sts.stdout | length > 0

    - name: Compute diff between current and desired manifests
      ansible.builtin.command:
        cmd: "diff -u /tmp/current-{{ release }}.yaml /tmp/desired-{{ release }}.yaml || true"
      register: manifest_diff
      failed_when: false
      changed_when: false

    - name: Show diff summary
      ansible.builtin.debug:
        msg: |
          Diff between current StatefulSet and desired Helm template (first 500 chars):
          {{ manifest_diff.stdout[:500] | default('No diff or files missing') }}

    - name: Detect immutable-field changes
      ansible.builtin.set_fact:
        immutable_diff_detected: "{{ (immutable_indicators | select('search', manifest_diff.stdout | default('')) | list) | length > 0 }}"

    - name: Report immutable-field detection
      ansible.builtin.debug:
        msg: "Immutable-field change detected: {{ immutable_diff_detected }}"

    - name: Fail with guidance when immutable change found and auto_approve is false
      ansible.builtin.fail:
        msg: |
          Immutable-field changes detected in StatefulSet for {{ release }}. To proceed safely:

            1) Inspect the diff above and confirm PVC names and selectors are compatible.
            2) If safe, re-run this play with -e auto_approve=true to allow deletion of the StatefulSet
               (PVCs will be preserved) and automatic helm upgrade.

          Example: ansible-playbook ansible/plays/loki_safe_upgrade.yaml -e values_file=/tmp/loki-values-revision-13.yaml -e auto_approve=true
      when: immutable_diff_detected and not auto_approve

    - name: Delete StatefulSet (preserve PVCs) when immutable change detected and auto_approve true
      ansible.builtin.command:
        cmd: "kubectl -n {{ namespace }} delete statefulset {{ release }}"
      when: immutable_diff_detected and auto_approve

    - name: Run helm upgrade (apply desired manifest)
      ansible.builtin.command:
        cmd: "helm upgrade -i --reset-values -f {{ values_file }} {{ release }} grafana/loki-stack --namespace {{ namespace }}"
      register: helm_upgrade
      failed_when: helm_upgrade.rc != 0

    - name: Show helm upgrade result
      ansible.builtin.debug:
        var: helm_upgrade.stdout_lines

    - name: Wait for pods to be ready (short watch)
      ansible.builtin.command:
        cmd: "kubectl -n {{ namespace }} get pods -l app.kubernetes.io/instance={{ release }} -o wide"
      register: pod_list
      failed_when: false
      changed_when: false

    - name: Show pod list
      ansible.builtin.debug:
        var: pod_list.stdout_lines
