---
- name: Clean up Loki index and chunk directories
  hosts: monitoring_nodes
  become: true
  tasks:
    - name: Optionally migrate existing Loki data into /srv/monitoring_data/loki
      block:
        - name: Create temporary migration directory
          ansible.builtin.file:
            path: /tmp/loki_migration
            state: directory
            mode: '0755'

        - name: Move existing /var/lib/loki into /srv/monitoring_data (if present)
          ansible.builtin.shell: |
            set -e
            if [ -d /var/lib/loki ]; then
              mv /var/lib/loki/* /srv/monitoring_data/loki/ || true
            fi
            if [ -d /tmp/loki ]; then
              mv /tmp/loki/* /srv/monitoring_data/loki/ || true
            fi
          args:
            warn: false

        - name: Remove temporary migration directory
          ansible.builtin.file:
            path: /tmp/loki_migration
            state: absent
      when: monitoring_migrate_existing | default(false)

    - name: Remove legacy and current Loki index and chunk directories (cleanup)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/loki/index
        - /tmp/loki/index_cache
        - /tmp/loki/chunks
        - /var/lib/loki/index
        - /var/lib/loki/index_cache
        - /var/lib/loki/chunks
        - /var/lib/loki/compactor
        - /srv/monitoring_data/loki/index
        - /srv/monitoring_data/loki/index_cache
        - /srv/monitoring_data/loki/chunks
        - /srv/monitoring_data/loki/compactor
      tags: loki_cleanup
- name: Loki Setup
  hosts: monitoring_nodes
  become: true
  tasks:
    - name: Ensure /etc/loki directory exists
      ansible.builtin.file:
        path: /etc/loki
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Ensure persistent Loki base directory exists
      ansible.builtin.file:
        path: /srv/monitoring_data/loki
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Ensure Loki index, chunk, and compactor directories exist under /srv/monitoring_data
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop:
        - /srv/monitoring_data/loki/index
        - /srv/monitoring_data/loki/index_cache
        - /srv/monitoring_data/loki/chunks
        - /srv/monitoring_data/loki/compactor
    - name: Ensure recursive ownership and permissions for /srv/monitoring_data/loki
      ansible.builtin.file:
        path: /srv/monitoring_data/loki
        owner: root
        group: root
        mode: '0755'
        recurse: yes

    - name: Download Loki binary
      ansible.builtin.get_url:
        url: https://github.com/grafana/loki/releases/download/v2.9.4/loki-linux-amd64.zip
        dest: /tmp/loki.zip
        mode: '0644'

    - name: Unzip Loki binary
      ansible.builtin.unarchive:
        src: /tmp/loki.zip
        dest: /usr/local/bin/
        remote_src: yes

    - name: Create Loki config file
      ansible.builtin.copy:
        dest: /etc/loki/loki-config.yaml
        content: |
          auth_enabled: false
          server:
            http_listen_port: 3100
          ingester:
            lifecycler:
              address: 127.0.0.1
              ring:
                kvstore:
                  store: inmemory
              final_sleep: 0s
            chunk_idle_period: 5m
            chunk_retain_period: 30s
            max_transfer_retries: 0
          schema_config:
            configs:
              - from: 2020-10-24
                store: boltdb-shipper
                object_store: filesystem
                schema: v11
                index:
                  prefix: index_
                  period: 24h
          storage_config:
            boltdb_shipper:
              active_index_directory: /srv/monitoring_data/loki/index
              cache_location: /srv/monitoring_data/loki/index_cache
              shared_store: filesystem
            filesystem:
              directory: /srv/monitoring_data/loki/chunks
          compactor:
            shared_store: filesystem
            working_directory: /srv/monitoring_data/loki/compactor
          limits_config:
            enforce_metric_name: false
            reject_old_samples: true
            reject_old_samples_max_age: 168h
          chunk_store_config:
            max_look_back_period: 0s
          table_manager:
            retention_deletes_enabled: true
            retention_period: 336h
        owner: root
        group: root
        mode: '0644'
      notify: Restart Loki

    - name: Create systemd service for Loki
      ansible.builtin.copy:
        dest: /etc/systemd/system/loki.service
        content: |
          [Unit]
          Description=Loki Log Aggregation System
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/loki-linux-amd64 -config.file=/etc/loki/loki-config.yaml
          Restart=always
          User=root
          Group=root

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd and start Loki
      ansible.builtin.systemd:
        name: loki
        state: started
        enabled: yes
        daemon_reload: yes

  handlers:
    - name: Restart Loki
      ansible.builtin.systemd:
        name: loki
        state: restarted
        daemon_reload: yes
