---
- name: Ensure Podman is installed and configured on all nodes
  hosts: all
  become: true
  tasks:
    - name: Install Podman on Debian
      apt:
        name: podman
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Podman on RedHat
      yum:
        name: podman
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Ensure podman socket is enabled and started (systemd)
      systemd:
        name: podman.socket
        state: started
        enabled: true
      when: ansible_service_mgr == 'systemd'

    - name: Create podman network for monitoring stack (idempotent)
      command: podman network exists monitoring || podman network create monitoring
      args:
        creates: /var/lib/containers/networks
      become: true
      changed_when: false
      failed_when: false
