

- name: Podman Metrics Exporter Setup
  hosts: all
  become: true
  tasks:

    - name: Add Podman repo key (Debian/Ubuntu)
      apt_key:
        url: 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/Release.key'
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add Podman upstream repository (Debian/Ubuntu)
      apt_repository:
        repo: 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/ /'
        state: present
      when: ansible_os_family == 'Debian'

    - name: Upgrade Podman to latest upstream version (Debian/Ubuntu)

---
- name: Podman Metrics Exporter Setup
  hosts: all
  become: true
  tasks:
    - name: Add Podman upstream repository (Debian/Ubuntu)
      apt_repository:
        repo: 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/ /'
        state: present
      when: ansible_os_family == 'Debian'
    - name: Add Podman repo key (Debian/Ubuntu)
      apt_key:
        url: 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/Release.key'
        state: present
      when: ansible_os_family == 'Debian'
    - name: Upgrade Podman to latest upstream version (Debian/Ubuntu)
      apt:
        name: podman
        state: latest
        update_cache: yes
      when: ansible_os_family == 'Debian'
    - name: Install Podman plugins for metrics (RHEL)
      yum:
        name: podman-plugins
        state: present
      when: ansible_os_family == 'RedHat'
    - name: Enable Podman REST API for Prometheus metrics
      copy:
        dest: /etc/systemd/system/podman-metrics.service
        content: |
          [Unit]
          Description=Podman REST API for Prometheus metrics
          After=network.target

          [Service]
          ExecStart=/usr/bin/podman system service --time=0 tcp:0.0.0.0:8080
          Restart=always
          User=root

          [Install]
          WantedBy=multi-user.target
      notify:
        - Reload systemd
        - Start podman-metrics
  handlers:
    - name: Reload systemd
      become: true
      systemd:
        daemon_reload: yes

    - name: Start podman-metrics
      become: true
      systemd:
        name: podman-metrics.service
        enabled: yes
        state: started
        content: |
          [Unit]
          Description=Podman REST API for Prometheus metrics
          After=network.target

          [Service]
          ExecStart=/usr/bin/podman system service --time=0 tcp:0.0.0.0:8080
          Restart=always
          User=root

          [Install]
          WantedBy=multi-user.target
      notify:
        - Reload systemd
        - Start podman-metrics
  handlers:
    - name: Reload systemd
      become: true
      systemd:
        daemon_reload: yes

    - name: Start podman-metrics
      become: true
      systemd:
        name: podman-metrics.service
        enabled: yes
        state: started
    - name: Start podman-metrics
      become: true
      systemd:
        name: podman-metrics.service
        enabled: yes
        state: started
