- name: Podman Metrics Exporter Setup
  hosts: all
  become: true
  tasks:
    - name: Install Podman plugins for metrics (Debian)
      apt:
        name: podman-plugins
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Podman plugins for metrics (RHEL)
      yum:
        name: podman-plugins
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Enable Podman REST API for Prometheus metrics
      copy:
        dest: /etc/systemd/system/podman-metrics.service
        content: |
          [Unit]
          Description=Podman REST API for Prometheus metrics
          After=network.target

          [Service]
          ExecStart=/usr/bin/podman system service --time=0 tcp:0.0.0.0:8080
          Restart=always
          User=root

          [Install]
          WantedBy=multi-user.target
      notify:
        - Reload systemd
        - Start podman-metrics
  handlers:
    - name: Reload systemd
      become: true
      systemd:
        daemon_reload: yes

    - name: Start podman-metrics
      become: true
      systemd:
        name: podman-metrics.service
        enabled: yes
        state: started
    - name: Start podman-metrics
      become: true
      systemd:
        name: podman-metrics.service
        enabled: yes
        state: started
