

- name: Podman Metrics Exporter Setup
  hosts: all
  become: true
  tasks:
    # ...existing code...
    - name: Add Podman repo key (Debian/Ubuntu)
      apt_key:
        url: 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/Release.key'
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add Podman upstream repository (Debian/Ubuntu)
      apt_repository:
        repo: 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/ /'
        state: present
      when: ansible_os_family == 'Debian'

    - name: Upgrade Podman to latest upstream version (Debian/Ubuntu)
      apt:
        name: podman
        state: latest
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Enable Podman metrics endpoint
      ansible.builtin.lineinfile:
        path: /etc/containers/containers.conf
        regexp: '^#?metrics_port ='
        line: 'metrics_port = 9882'
        state: present
        create: yes
      # No handler needed; explicit restart task follows
      tags: metrics

    - name: Ensure Podman service is restarted to apply metrics config
      ansible.builtin.systemd:
        name: podman
        state: restarted
        enabled: yes
      when: ansible_service_mgr == 'systemd'
      tags: metrics

    - name: Deploy promtail container
      containers.podman.podman_container:
        name: promtail
        image: docker.io/grafana/promtail:latest
        state: started
        volumes:
          - /var/log:/var/log:ro
          - /etc/promtail:/etc/promtail:ro
        restart_policy: always
        command: -config.file=/etc/promtail/promtail.yaml
      tags: logs

    - name: Ensure firewall allows Prometheus/Loki scraping
      ansible.builtin.ufw:
        rule: allow
        port: "9882,3100"
        proto: tcp
      when: ansible_os_family == 'Debian'
      tags: firewall
