- name: Update Prometheus scrape config for Podman metrics
  hosts: monitoring_nodes
  become: true
  tasks:
    - name: Ensure Prometheus scrape config includes Podman endpoints
      copy:
        dest: /etc/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 15s
          scrape_configs:
            - job_name: 'node_exporters'
              static_configs:
                - targets:
                    - '192.168.4.61:9100'
                    - '192.168.4.62:9100'
                    - '192.168.4.63:9100'
            - job_name: 'podman_apps'
              static_configs:
                - targets:
                    - '192.168.4.61:8080'
                    - '192.168.4.62:8080'
                    - '192.168.4.63:8080'
              metrics_path: /metrics
            # Add more scrape configs as needed
