- name: Deploy Prometheus container
  hosts: all
  become: true
  vars:
    prometheus_image: docker.io/prom/prometheus:latest
    prometheus_container: prometheus
    prometheus_data_dir: /srv/monitoring_data/prometheus
    prometheus_host_port: 9090
  tasks:
    - name: Ensure Prometheus data directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop:
        - "{{ prometheus_data_dir }}"
        - "{{ prometheus_data_dir }}/data"
      tags: prometheus

    - name: Pull Prometheus image
      ansible.builtin.command:
        cmd: podman pull {{ prometheus_image }}
      register: prometheus_pull
      changed_when: prometheus_pull.rc == 0
      failed_when: prometheus_pull.rc != 0
      tags: prometheus

    - name: Check if port {{ prometheus_host_port }} is available
      ansible.builtin.command:
        cmd: ss -ltn "sport = :{{ prometheus_host_port }}" || true
      register: port_check
      changed_when: false
      tags: prometheus

    - name: Fail if port {{ prometheus_host_port }} is in use
      ansible.builtin.fail:
        msg: "Port {{ prometheus_host_port }} appears to be in use on the target. Stop the process or choose a different port before deploying Prometheus. Output: {{ port_check.stdout }}"
      when: port_check.stdout != ""
      tags: prometheus

    - name: Remove existing Prometheus container if present
      ansible.builtin.command:
        cmd: podman rm -f {{ prometheus_container }}
      register: prometheus_rm
      failed_when: false
      changed_when: prometheus_rm.rc == 0
      tags: prometheus

    - name: Copy static prometheus.yml
      ansible.builtin.copy:
        src: ../files/prometheus.yml
        dest: /srv/monitoring_data/prometheus/prometheus.yml
        owner: root
        group: root
        mode: '0644'
      tags: prometheus

    - name: Run Prometheus container
      ansible.builtin.command:
        cmd: >-
          podman run -d --name {{ prometheus_container }} --rm -p {{ prometheus_host_port }}:9090
          -v {{ prometheus_data_dir }}:/etc/prometheus:Z
          -v {{ prometheus_data_dir }}/data:/prometheus:Z
          {{ prometheus_image }}
      register: prometheus_run
      changed_when: prometheus_run.rc == 0
      failed_when: prometheus_run.rc != 0
      tags: prometheus

    - name: Wait for Prometheus to be ready
      ansible.builtin.uri:
        url: "http://localhost:{{ prometheus_host_port }}/-/ready"
        status_code: 200
        timeout: 10
      register: prometheus_ready
      retries: 6
      delay: 5
      until: prometheus_ready.status == 200
      tags: prometheus
