---
- hosts: debian_nodes
  become: true
  tasks:
    - name: Remove Tailscale
      apt:
        name: tailscale
        state: absent
      ignore_errors: true
    - name: Remove Keepalived
      apt:
        name: keepalived
        state: absent
      ignore_errors: true
    - name: Remove custom Tailscale interface config
      file:
        path: /etc/network/interfaces.d/tailscale
        state: absent
      ignore_errors: true
    - name: Remove custom Keepalived config
      file:
        path: /etc/keepalived/keepalived.conf
        state: absent
      ignore_errors: true
    - name: Remove k3s
      command: "/usr/local/bin/k3s-uninstall.sh"
      args:
        removes: /usr/local/bin/k3s-uninstall.sh
      ignore_errors: true
    - name: Remove k3s agent
      command: "/usr/local/bin/k3s-agent-uninstall.sh"
      args:
        removes: /usr/local/bin/k3s-agent-uninstall.sh
      ignore_errors: true
    - name: Remove k3s certificates
      file:
        path: /etc/rancher/k3s
        state: absent
      ignore_errors: true
    - name: Remove k3s install settings
      file:
        path: /var/lib/rancher/k3s
        state: absent
      ignore_errors: true
    - name: Remove other non-essential packages
      apt:
        name:
          - docker.io
          - docker-compose
          - podman
        state: absent
      ignore_errors: true
    - name: Reboot node (optional)
      reboot:
        msg: "Rebooting to apply clean state."
        pre_reboot_delay: 5
      when: ansible_facts['os_family'] == 'Debian'
