---
# Setup monitoring prerequisites before deployment
# This ensures directories and permissions are correct for the monitoring stack
- name: Setup monitoring prerequisites
  hosts: monitoring_nodes
  become: true
  gather_facts: true
  vars:
    # A fixed default root for monitoring data. Users may still override
    # `monit_root` via inventory or extra-vars; we will use the default filter
    # at each use site to avoid self-referential templating.
    monitoring_default_root: '/srv/monitoring_data'
    monitoring_subdirs:
      - "{{ monit_root | default(monitoring_default_root) }}/grafana"
      - "{{ monit_root | default(monitoring_default_root) }}/grafana/dashboards"
      - "{{ monit_root | default(monitoring_default_root) }}/grafana/datasources"
      - "{{ monit_root | default(monitoring_default_root) }}/grafana/data"
      - "{{ monit_root | default(monitoring_default_root) }}/prometheus"
      - "{{ monit_root | default(monitoring_default_root) }}/prometheus/data"
      - "{{ monit_root | default(monitoring_default_root) }}/loki"
      - "{{ monit_root | default(monitoring_default_root) }}/loki/chunks"
      - "{{ monit_root | default(monitoring_default_root) }}/loki/index"
      - "{{ monit_root | default(monitoring_default_root) }}/promtail"
      - "{{ monit_root | default(monitoring_default_root) }}/promtail/data"
      - "{{ monit_root | default(monitoring_default_root) }}/local-path-provisioner"
      - "/var/log"
      - "/var/promtail"
      - "/opt/promtail"

  tasks:
    - name: Display monitoring setup info
      debug:
        msg: |
          Setting up monitoring prerequisites...
          Monitoring root: {{ monit_root | default(monitoring_default_root) }}
          Target node: {{ inventory_hostname }}

    - name: Create monitoring root directory
      file:
        path: "{{ monit_root | default(monitoring_default_root) }}"
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Create monitoring subdirectories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: root
        group: root
      loop: "{{ monitoring_subdirs }}"
      when: item != "/var/log"  # Don't try to create /var/log

    - name: Set SELinux contexts for monitoring directories (if SELinux enabled)
      command: |
        semanage fcontext -a -t container_file_t "{{ monit_root | default(monitoring_default_root) }}(/.*)?" || true
        restorecon -Rv "{{ monit_root | default(monitoring_default_root) }}" || true
      ignore_errors: true
      when: ansible_selinux is defined and ansible_selinux.status == "enabled"

    - name: Set SELinux booleans for container access (if SELinux enabled)
      seboolean:
        name: "{{ item }}"
        state: true
        persistent: true
      loop:
        - container_use_cephfs
        - container_manage_cgroup
      ignore_errors: true
      when: ansible_selinux is defined and ansible_selinux.status == "enabled"

    - name: Check monitoring directory permissions
      stat:
        path: "{{ monit_root | default(monitoring_default_root) }}"
      register: monit_dir_stat

    - name: Display monitoring setup results
      debug:
        msg: |
          ✓ Monitoring prerequisites setup completed
          Directory: {{ monit_dir_stat.stat.path }}
          Permissions: {{ monit_dir_stat.stat.mode }}
          Owner: {{ monit_dir_stat.stat.pw_name }}:{{ monit_dir_stat.stat.gr_name }}