---
# HostPath PersistentVolume for Loki (homelab fallback)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv
  labels:
    vmstation.io/component: monitoring
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /srv/monitoring_data/loki
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
  claimRef:
    namespace: monitoring
    name: loki-data-loki-0
