apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-paperless-input
  labels:
    app: brother-gateway
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /srv/paperless-input
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - storagenodet3500.vmstation.local
