apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-scan-storage
  namespace: printer-ops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
