apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-input-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
  volumeMode: Filesystem
