apiVersion: v1
kind: ConfigMap
metadata:
  name: jellyfin-config
  namespace: jellyfin
  labels:
    app: jellyfin
    component: config
data:
  # Jellyfin encoding configuration for hardware acceleration
  encoding.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <EncodingOptions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <TranscodingTempPath>/config/transcoding-temp</TranscodingTempPath>
      <EncoderAppPath>/usr/lib/jellyfin-ffmpeg/ffmpeg</EncoderAppPath>
      <EncoderAppPathDisplay>/usr/lib/jellyfin-ffmpeg/ffmpeg</EncoderAppPathDisplay>
      <VaapiDevice>/dev/dri/renderD128</VaapiDevice>
      <EnableHardwareEncoding>true</EnableHardwareEncoding>
      <AllowHevcEncoding>true</AllowHevcEncoding>
      <EnableHardwareDecoding>true</EnableHardwareDecoding>
      <EnableDecodingColorDepth10Hevc>true</EnableDecodingColorDepth10Hevc>
      <EnableDecodingColorDepth10Vp9>true</EnableDecodingColorDepth10Vp9>
      <EnableEnhancedNvdecDecoder>true</EnableEnhancedNvdecDecoder>
      <PreferSystemNativeHwDecoder>true</PreferSystemNativeHwDecoder>
      <EnableIntelLowPowerH264HwEncoder>true</EnableIntelLowPowerH264HwEncoder>
      <EnableIntelLowPowerHevcHwEncoder>true</EnableIntelLowPowerHevcHwEncoder>
      <EnableHardwareFilterUpscaling>true</EnableHardwareFilterUpscaling>
      <AllowAv1Encoding>true</AllowAv1Encoding>
      <AllowOnDemandMetadataBasedKeyframeExtractionForExtensions>
        <string>mkv</string>
        <string>mp4</string>
        <string>mov</string>
        <string>avi</string>
        <string>m4v</string>
        <string>asf</string>
        <string>webm</string>
        <string>wmv</string>
        <string>ts</string>
        <string>mpg</string>
        <string>mpeg</string>
        <string>m2v</string>
        <string>m2ts</string>
        <string>mts</string>
        <string>3gp</string>
        <string>3g2</string>
        <string>f4v</string>
        <string>ogv</string>
        <string>divx</string>
      </AllowOnDemandMetadataBasedKeyframeExtractionForExtensions>
      <HardwareDecodingCodecs>
        <string>h264</string>
        <string>hevc</string>
        <string>mpeg2video</string>
        <string>mpeg4</string>
        <string>vc1</string>
        <string>vp8</string>
        <string>vp9</string>
        <string>av1</string>
      </HardwareDecodingCodecs>
      <MaxMuxingQueueSize>2048</MaxMuxingQueueSize>
      <EnableSubtitleExtraction>true</EnableSubtitleExtraction>
      <DownMixAudioBoost>2</DownMixAudioBoost>
      <MaximumEncodingThreads>0</MaximumEncodingThreads>
    </EncodingOptions>

  # Network configuration for high-bandwidth streaming
  network.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <NetworkConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <RequireHttps>false</RequireHttps>
      <CertificatePath></CertificatePath>
      <CertificatePassword></CertificatePassword>
      <BaseUrl></BaseUrl>
      <PublicHttpsPort>8920</PublicHttpsPort>
      <HttpServerPortNumber>8096</HttpServerPortNumber>
      <HttpsPortNumber>8920</HttpsPortNumber>
      <EnableHttps>false</EnableHttps>
      <PublicPort>8096</PublicPort>
      <UPnPCreateHttpPortMap>false</UPnPCreateHttpPortMap>
      <UDPPortRange></UDPPortRange>
      <EnableIPV6>false</EnableIPV6>
      <EnableIPV4>true</EnableIPV4>
      <EnableSSDPTracing>false</EnableSSDPTracing>
      <SSDPTracingFilter></SSDPTracingFilter>
      <UDPSendCount>2</UDPSendCount>
      <UDPSendDelay>100</UDPSendDelay>
      <IgnoreVirtualInterfaces>true</IgnoreVirtualInterfaces>
      <VirtualInterfaceNames>vEthernet*</VirtualInterfaceNames>
      <GatewayMonitorPeriod>60</GatewayMonitorPeriod>
      <TrustAllIP6Interfaces>false</TrustAllIP6Interfaces>
      <HDHomerunPortRange></HDHomerunPortRange>
      <PublishedServerUriBySubnet />
      <AutoDiscoveryTracing>false</AutoDiscoveryTracing>
      <AutoDiscovery>true</AutoDiscovery>
      <RemoteIPFilter />
      <IsRemoteIPFilterBlacklist>false</IsRemoteIPFilterBlacklist>
      <EnableRemoteAccess>true</EnableRemoteAccess>
      <LocalNetworkSubnets>
        <string>192.168.4.0/24</string>
        <string>10.244.0.0/16</string>
      </LocalNetworkSubnets>
      <LocalNetworkAddresses />
      <KnownProxies />
      <EnablePublishedServerUriByRequest>false</EnablePublishedServerUriByRequest>
    </NetworkConfiguration>

  # System configuration for performance
  system.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <ServerConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <IsStartupWizardCompleted>false</IsStartupWizardCompleted>
      <CachePath>/config/cache</CachePath>
      <ProgramDataPath>/config</ProgramDataPath>
      <MetadataPath>/config/metadata</MetadataPath>
      <InternalMetadataPath>/config/metadata</InternalMetadataPath>
      <ItemsByNamePath>/config/metadata/People</ItemsByNamePath>
      <TranscodingTempPath>/config/transcoding-temp</TranscodingTempPath>
      <CertificatePath></CertificatePath>
      <IsPortAuthorized>true</IsPortAuthorized>
      <QuickConnectAvailable>true</QuickConnectAvailable>
      <EnableRemoteAccess>true</EnableRemoteAccess>
      <EnableUPnP>false</EnableUPnP>
      <EnableMetrics>true</EnableMetrics>
      <PublicPort>8096</PublicPort>
      <PublicHttpsPort>8920</PublicHttpsPort>
      <HttpServerPortNumber>8096</HttpServerPortNumber>
      <HttpsPortNumber>8920</HttpsPortNumber>
      <EnableHttps>false</EnableHttps>
      <EnableDashboardResponseCaching>true</EnableDashboardResponseCaching>
      <EnableCaseSensitiveItemIds>true</EnableCaseSensitiveItemIds>
      <DisableLiveTvChannelUserDataName>true</DisableLiveTvChannelUserDataName>
      <MetadataRefreshConcurrency>2</MetadataRefreshConcurrency>
      <LibraryMetadataRefreshConcurrency>2</LibraryMetadataRefreshConcurrency>
      <LibraryScanFanoutConcurrency>1</LibraryScanFanoutConcurrency>
      <LibraryMetadataRefreshConcurrency>2</LibraryMetadataRefreshConcurrency>
      <RemoveOldPlugins>true</RemoveOldPlugins>
      <AllowClientLogUpload>false</AllowClientLogUpload>
      <DummyChapterDuration>300</DummyChapterDuration>
      <ChapterImageResolution>1920</ChapterImageResolution>
      <ParallelImageEncodingLimit>0</ParallelImageEncodingLimit>
      <EnableFolderView>false</EnableFolderView>
      <EnableGroupingIntoCollections>true</EnableGroupingIntoCollections>
      <DisplaySpecialsWithinSeasons>true</DisplaySpecialsWithinSeasons>
      <CodecsUsed />
      <PluginRepositories>
        <RepositoryInfo>
          <Name>Jellyfin Stable</Name>
          <Url>https://repo.jellyfin.org/releases/plugin/manifest-stable.json</Url>
          <Enabled>true</Enabled>
        </RepositoryInfo>
      </PluginRepositories>
      <EnableExternalContentInSuggestions>true</EnableExternalContentInSuggestions>
      <ImageExtractionTimeoutMs>0</ImageExtractionTimeoutMs>
      <PathSubstitutions />
      <UninstalledPlugins />
      <CollapseVideoFolders>true</CollapseVideoFolders>
      <EnablePeoplePrefixSubFolders>true</EnablePeoplePrefixSubFolders>
      <UICulture>en-US</UICulture>
      <MetadataCountryCode>US</MetadataCountryCode>
      <SortReplaceCharacters>
        <string>.</string>
        <string>+</string>
        <string>%</string>
      </SortReplaceCharacters>
      <SortRemoveCharacters>
        <string>,</string>
        <string>&amp;</string>
        <string>-</string>
        <string>{</string>
        <string>}</string>
        <string>'</string>
      </SortRemoveCharacters>
      <SortRemoveWords>
        <string>the</string>
        <string>a</string>
        <string>an</string>
      </SortRemoveWords>
      <MinResumePct>5</MinResumePct>
      <MaxResumePct>90</MaxResumePct>
      <MinResumeDurationSeconds>300</MinResumeDurationSeconds>
      <MinAudiobookResume>5</MinAudiobookResume>
      <MaxAudiobookResume>5</MaxAudiobookResume>
      <LibraryMonitorDelay>60</LibraryMonitorDelay>
      <EnableDashboardResourceMinification>true</EnableDashboardResourceMinification>
      <ImageSavingConvention>Compatible</ImageSavingConvention>
      <PublicSystemInfo>true</PublicSystemInfo>
      <QuickConnectAvailable>true</QuickConnectAvailable>
    </ServerConfiguration>