apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      nodeSelector:
        kubernetes.io/hostname: storagenodet3500
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin:latest
        ports:
        - containerPort: 8096
          name: http
        volumeMounts:
        - name: media
          mountPath: /srv/media
          readOnly: true
        - name: config
          mountPath: /jellyfin
      volumes:
      - name: media
        hostPath:
          path: /srv/media
          type: Directory
      - name: config
        persistentVolumeClaim:
          claimName: jellyfin-config-pvc