apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: jellyfin-hpa
  namespace: jellyfin
  labels:
    app: jellyfin
    component: media-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jellyfin
  minReplicas: 1
  maxReplicas: 3  # Maximum 3 pods due to 8GB RAM constraint (3 * 2.5GB = 7.5GB)
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60  # Scale up when CPU > 60%
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70  # Scale up when memory > 70%
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5 minutes before scaling down
      policies:
      - type: Percent
        value: 50  # Scale down by 50% at most
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60   # Quick scale up for responsive streaming
      policies:
      - type: Percent
        value: 100  # Double the replicas quickly when needed
        periodSeconds: 60
      selectPolicy: Max