---
# HostPath PersistentVolume for Grafana (homelab/dev fallback)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  labels:
    app: grafana
    vmstation.io/component: monitoring
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /srv/monitoring_data/grafana
    type: DirectoryOrCreate
  claimRef:
    namespace: monitoring
    name: grafana-pvc

---
# PVC for Grafana (note: namespace monitoring)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
