---
# HostPath PersistentVolume for Loki (homelab fallback)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv
  labels:
    vmstation.io/component: monitoring
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /srv/monitoring_data/loki
    type: DirectoryOrCreate

---
# PVC for Loki to request the hostPath PV
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-storage
