---
# ansible/roles/rke2/handlers/main.yml
# Handlers for RKE2 role

- name: restart rke2-server
  systemd:
    name: rke2-server
    state: restarted
    daemon_reload: yes
  become: true

- name: reload systemd
  systemd:
    daemon_reload: yes
  become: true

- name: restart NetworkManager
  systemd:
    name: NetworkManager
    state: restarted
  become: true
  when: ansible_os_family == "RedHat"
