apiVersion: v1
kind: PersistentVolume
metadata:
  name: brother-scans-pv
  labels:
    app: brother-gateway
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /srv/media/family-files/brother-scans
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - storagenodet3500
