apiVersion: v1
kind: ConfigMap
metadata:
  name: jellyfin-config
  namespace: jellyfin
data:
  # Jellyfin server configuration optimized for 4K streaming
  network.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <NetworkConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <EnableHttps>false</EnableHttps>
      <RequireHttps>false</RequireHttps>
      <BaseUrl />
      <PublicHttpsPort>8920</PublicHttpsPort>
      <HttpServerPortNumber>8096</HttpServerPortNumber>
      <HttpsPortNumber>8920</HttpsPortNumber>
      <EnableRemoteAccess>true</EnableRemoteAccess>
      <EnableAutomaticPortMapping>false</EnableAutomaticPortMapping>
      <PublicPort>8096</PublicPort>
      <UPnPCreateHttpPortMap>false</UPnPCreateHttpPortMap>
      <LocalNetworkSubnets>
        <string>192.168.4.0/24</string>
        <string>10.244.0.0/16</string>
      </LocalNetworkSubnets>
      <LocalNetworkAddresses />
      <KnownProxies />
      <IsRemoteIPFilterBlacklist>false</IsRemoteIPFilterBlacklist>
      <RemoteIPFilter />
    </NetworkConfiguration>
  
  encoding.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <EncodingOptions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <TranscodingTempPath>/tmp/jellyfin</TranscodingTempPath>
      <FallbackFontPath />
      <EnableFallbackFont>false</EnableFallbackFont>
      <DownMixAudioBoost>2</DownMixAudioBoost>
      <MaxMuxingQueueSize>2048</MaxMuxingQueueSize>
      <EnableThrottling>false</EnableThrottling>
      <ThrottleDelaySeconds>180</ThrottleDelaySeconds>
      <HardwareAccelerationType>none</HardwareAccelerationType>
      <EncoderAppPath />
      <EncoderAppPathDisplay />
      <VaapiDevice />
      <EnableTonemapping>false</EnableTonemapping>
      <EnableVppTonemapping>false</EnableVppTonemapping>
      <TonemappingAlgorithm>hable</TonemappingAlgorithm>
      <TonemappingMode>auto</TonemappingMode>
      <TonemappingRange>auto</TonemappingRange>
      <TonemappingDesat>0</TonemappingDesat>
      <TonemappingPeak>100</TonemappingPeak>
      <TonemappingParam>0</TonemappingParam>
      <VppTonemappingBrightness>0</VppTonemappingBrightness>
      <VppTonemappingContrast>1.2</VppTonemappingContrast>
      <H264Crf>21</H264Crf>
      <H265Crf>21</H265Crf>
      <EncoderPreset>veryfast</EncoderPreset>
      <DeinterlaceDoubleRate>false</DeinterlaceDoubleRate>
      <DeinterlaceMethod>yadif</DeinterlaceMethod>
      <EnableDecodingColorDepth10Hevc>true</EnableDecodingColorDepth10Hevc>
      <EnableDecodingColorDepth10Vp9>true</EnableDecodingColorDepth10Vp9>
      <EnableEnhancedNvdecDecoder>false</EnableEnhancedNvdecDecoder>
      <PreferSystemNativeHwDecoder>false</PreferSystemNativeHwDecoder>
      <EnableIntelLowPowerH264HwEncoder>false</EnableIntelLowPowerH264HwEncoder>
      <EnableIntelLowPowerHevcHwEncoder>false</EnableIntelLowPowerHevcHwEncoder>
      <EnableHardwareEncoding>false</EnableHardwareEncoding>
      <AllowHevcEncoding>true</AllowHevcEncoding>
      <EnableSubtitleExtraction>true</EnableSubtitleExtraction>
      <HardwareDecodingCodecs>
        <string>h264</string>
        <string>hevc</string>
        <string>mpeg2video</string>
        <string>vc1</string>
        <string>vp8</string>
        <string>vp9</string>
        <string>av1</string>
      </HardwareDecodingCodecs>
      <AllowOnDemandMetadataBasedKeyframeExtractionForExtensions>
        <string>mkv</string>
      </AllowOnDemandMetadataBasedKeyframeExtractionForExtensions>
    </EncodingOptions>