---
# VMStation Jellyfin Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin
  labels:
    name: jellyfin
    vmstation.io/component: media
---
# Jellyfin Pod (using hostPath volumes instead of PVCs)
apiVersion: v1
kind: Pod
metadata:
  name: jellyfin
  namespace: jellyfin
  labels:
    app: jellyfin
    component: media-server
spec:
  # Schedule on storage node explicitly
  nodeSelector:
    kubernetes.io/hostname: storagenodet3500
  # Security context: run as non-root user
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  containers:
  - name: jellyfin
    image: jellyfin/jellyfin:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8096
      name: http
    - containerPort: 8920
      name: https
    - containerPort: 1900
      name: dlna
      protocol: UDP
    - containerPort: 7359
      name: discovery
      protocol: UDP
    env:
    - name: JELLYFIN_PublishedServerUrl
      value: "http://192.168.4.61:30096"
    volumeMounts:
    - name: jellyfin-config
      mountPath: /config
    - name: jellyfin-cache
      mountPath: /cache
    - name: jellyfin-media
      mountPath: /media
      readOnly: true
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 2000m
        memory: 2Gi
    # Improved health checks using web interface
    livenessProbe:
      httpGet:
        path: /web/index.html
        port: 8096
        scheme: HTTP
      initialDelaySeconds: 180
      periodSeconds: 60
      timeoutSeconds: 30
      failureThreshold: 5
    readinessProbe:
      httpGet:
        path: /web/index.html
        port: 8096
        scheme: HTTP
      initialDelaySeconds: 120
      periodSeconds: 30
      timeoutSeconds: 15
      failureThreshold: 5
    startupProbe:
      httpGet:
        path: /web/index.html
        port: 8096
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 30
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      capabilities:
        drop:
        - ALL
  # Use hostPath volumes directly (no PVCs needed)
  volumes:
  - name: jellyfin-config
    hostPath:
      path: /var/lib/jellyfin
      type: DirectoryOrCreate
  - name: jellyfin-cache
    emptyDir:
      sizeLimit: 10Gi
  - name: jellyfin-media
    hostPath:
      path: /srv/media
      type: DirectoryOrCreate
  restartPolicy: Always
---
# Jellyfin Service
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service
  namespace: jellyfin
  labels:
    app: jellyfin
    component: media-server
spec:
  type: NodePort
  ports:
  - port: 8096
    targetPort: 8096
    nodePort: 30096
    name: http
  - port: 8920
    targetPort: 8920
    nodePort: 30920
    name: https
  selector:
    app: jellyfin
    component: media-server