apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone
  namespace: kube-system
secrets:
  - name: drone-token
---
apiVersion: v1
kind: Secret
metadata:
  name: drone-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: drone
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: drone-pipeline-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: drone
  namespace: kube-system