---
# =============================================================================
# Setup Auto-Sleep Monitoring - Install cron job for hourly resource checks
# =============================================================================

- name: Setup auto-sleep monitoring on masternode
  hosts: monitoring_nodes
  become: true
  tasks:
    - name: Ensure wakeonlan package is installed
      ansible.builtin.package:
        name: wakeonlan
        state: present
      when: ansible_os_family == 'Debian'

    - name: Ensure wakeonlan package is installed (RHEL)
      ansible.builtin.package:
        name: wol
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Ensure log file exists
      ansible.builtin.file:
        path: /var/log/vmstation-autosleep.log
        state: touch
        owner: root
        group: root
        mode: '0644'

    - name: Make sleep/wake scripts executable
      ansible.builtin.file:
        path: "{{ item }}"
        mode: '0755'
      loop:
        - /root/VMStation/ansible/playbooks/trigger-sleep.sh
        - /root/VMStation/ansible/playbooks/wake-cluster.sh

    - name: Setup hourly cron job for resource monitoring
      ansible.builtin.cron:
        name: "VMStation Auto-Sleep Monitor"
        minute: "0"
        hour: "*"
        job: "cd /root/VMStation && ansible-playbook -i ansible/inventory/hosts ansible/playbooks/monitor-resources.yaml >> /var/log/vmstation-autosleep.log 2>&1"
        user: root
        state: present

    - name: Display setup completion message
      ansible.builtin.debug:
        msg: |
          ✅ Auto-sleep monitoring configured successfully
          
          - Cron job: Hourly resource checks
          - Log file: /var/log/vmstation-autosleep.log
          - Sleep script: /root/VMStation/ansible/playbooks/trigger-sleep.sh
          - Wake script: /root/VMStation/ansible/playbooks/wake-cluster.sh
          
          Cluster will automatically sleep after 2 hours of inactivity when:
          - No Jellyfin sessions active
          - CPU utilization < 20%
          - No recent user activity
          - No active Kubernetes jobs
          
          To manually wake cluster: /root/VMStation/ansible/playbooks/wake-cluster.sh
