---
- name: Spin down cluster (safe, idempotent)
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    # These can be overridden via --extra-vars
    spin_targets: []
    allow_power_down: false
    spin_confirm: false
    apps_to_manage: []
    delete_local_data: false
    drain_grace_period: 60
  roles:
    - role: cluster-spindown
