---
# =============================================================================
# VMStation RKE2 Uninstallation
# Remove RKE2 from homelab RHEL10 node
# =============================================================================

- name: "RKE2 Uninstallation - Homelab Node"
  hosts: compute_nodes
  gather_facts: false
  become: true
  tasks:
    - name: "Display RKE2 uninstall banner"
      debug:
        msg: |
          ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
          RKE2 Uninstallation on Homelab
          Target: {{ inventory_hostname }}
          ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    - name: "Check if RKE2 is installed"
      stat:
        path: /usr/local/bin/rke2-uninstall.sh
      register: rke2_uninstall_script

    - name: "Run RKE2 uninstall script"
      shell: /usr/local/bin/rke2-uninstall.sh
      when: rke2_uninstall_script.stat.exists
      failed_when: false

    - name: "Remove RKE2 directories"
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/rancher/rke2
        - /var/lib/rancher/rke2
        - /usr/local/bin/rke2
      failed_when: false

    - name: "Remove RKE2 environment script"
      file:
        path: /etc/profile.d/rke2.sh
        state: absent
      failed_when: false

    - name: "Display uninstall complete message"
      debug:
        msg: |
          ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
          ✅ RKE2 Uninstallation Complete
          
          Node: {{ inventory_hostname }}
          RKE2 removed successfully
          ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
