---
# =============================================================================
# VMStation CNI Downloads Verification Playbook
# Verifies CNI plugin installation and architecture detection
# =============================================================================

- name: Verify CNI plugin downloads and installation
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Display node architecture
      ansible.builtin.debug:
        msg: "Node: {{ inventory_hostname }}, Arch: {{ ansible_architecture }}, Mapped CNI arch: {{ 'amd64' if ansible_architecture == 'x86_64' else ('arm64' if ansible_architecture == 'aarch64' else ansible_architecture) }}"

    - name: Check if /opt/cni/bin directory exists
      ansible.builtin.stat:
        path: /opt/cni/bin
      register: cni_dir

    - name: Verify CNI directory exists
      ansible.builtin.assert:
        that:
          - cni_dir.stat.exists
          - cni_dir.stat.isdir
        fail_msg: "CNI directory /opt/cni/bin does not exist on {{ inventory_hostname }}"
        success_msg: "CNI directory /opt/cni/bin exists on {{ inventory_hostname }}"

    - name: List CNI plugins installed
      ansible.builtin.find:
        paths: /opt/cni/bin
        file_type: file
      register: cni_plugins

    - name: Verify CNI plugins present
      ansible.builtin.assert:
        that:
          - cni_plugins.files | length > 0
        fail_msg: "No CNI plugins found in /opt/cni/bin on {{ inventory_hostname }}"
        success_msg: "Found {{ cni_plugins.files | length }} CNI plugins on {{ inventory_hostname }}"

    - name: Check for required CNI plugins
      ansible.builtin.stat:
        path: "/opt/cni/bin/{{ item }}"
      loop:
        - loopback
        - bridge
        - host-local
        - portmap
      register: required_plugins

    - name: Verify required plugins exist
      ansible.builtin.assert:
        that:
          - item.stat.exists
        fail_msg: "Required CNI plugin {{ item.item }} missing on {{ inventory_hostname }}"
        success_msg: "Required CNI plugin {{ item.item }} present on {{ inventory_hostname }}"
      loop: "{{ required_plugins.results }}"

    - name: Check if temporary CNI archive still exists
      ansible.builtin.stat:
        path: /tmp/cni-plugins.tgz
      register: temp_archive

    - name: Verify temporary files cleaned up
      ansible.builtin.debug:
        msg: "{{ 'WARNING: Temporary CNI archive still present on ' + inventory_hostname if temp_archive.stat.exists else 'Temporary files cleaned up on ' + inventory_hostname }}"

- name: Summary
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Display verification summary
      ansible.builtin.debug:
        msg:
          - "==================================================="
          - "CNI Plugin Verification Complete"
          - "==================================================="
          - "All nodes have been verified for CNI plugin installation."
          - "Architecture-specific downloads are working correctly."
          - "Run: kubectl get nodes -o wide"
          - "Expected: All nodes should be Ready with CNI configured"
          - "==================================================="
