---
- name: Ensure artifacts directory exists on control host
  delegate_to: localhost
  run_once: true
  ansible.builtin.file:
    path: "{{ playbook_dir }}/../ansible/artifacts"
    state: directory
    mode: '0755'

- name: Gather node networking facts
  become: true
  ansible.builtin.shell: |
    echo '=== {{ inventory_hostname }}: ip addr ===' > /tmp/{{ inventory_hostname }}.netdiag.txt
    ip addr >> /tmp/{{ inventory_hostname }}.netdiag.txt
    echo '\n=== routes ===' >> /tmp/{{ inventory_hostname }}.netdiag.txt
    ip route >> /tmp/{{ inventory_hostname }}.netdiag.txt
    echo '\n=== iptables -S ===' >> /tmp/{{ inventory_hostname }}.netdiag.txt
    iptables -S >> /tmp/{{ inventory_hostname }}.netdiag.txt || true
    echo '\n=== lsmod ===' >> /tmp/{{ inventory_hostname }}.netdiag.txt
    lsmod >> /tmp/{{ inventory_hostname }}.netdiag.txt
  register: netdiag

- name: Fetch diagnostics to controller
  fetch:
    src: "/tmp/{{ inventory_hostname }}.netdiag.txt"
    dest: "{{ playbook_dir }}/../ansible/artifacts/"
    flat: yes
