---
# Playbook to apply network fixes across all nodes and optionally restart CNI components
- hosts: all
  become: true
  roles:
    - role: network-fix

- hosts: masternode
  become: true
  tasks:
    - name: Restart flannel daemonset pods on control plane
      ansible.builtin.shell: |
        kubectl -n kube-system rollout restart daemonset/kube-flannel-ds || true
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      args:
        warn: false

    - name: Restart kube-proxy
      ansible.builtin.shell: |
        kubectl -n kube-system rollout restart daemonset/kube-proxy || true
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      args:
        warn: false

    - name: Wait for flannel daemonset rollout to finish
      ansible.builtin.shell: |
        kubectl -n kube-system rollout status daemonset/kube-flannel-ds --timeout=120s || true
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      args:
        warn: false

    - name: Wait for kube-proxy daemonset rollout to finish
      ansible.builtin.shell: |
        kubectl -n kube-system rollout status daemonset/kube-proxy --timeout=120s || true
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      args:
        warn: false
