---
- name: Debug monitoring stack and collect information
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Check podman status
      command: podman --version
      register: podman_version
      ignore_errors: true

    - name: List running containers
      command: podman ps
      register: running_containers
      ignore_errors: true

    - name: Check systemd status for monitoring services
      command: systemctl status podman.socket
      register: podman_socket_status
      ignore_errors: true

    - name: Display collected information
      debug:
        msg:
          - "Podman version: {{ podman_version.stdout | default('Not available') }}"
          - "Running containers: {{ running_containers.stdout_lines | default(['None']) }}"
          - "Podman socket status: {{ podman_socket_status.stdout | default('Not available') }}"
