---
- name: Publish podman-system-metrics image to local registry and configure nodes
  hosts: monitoring_nodes
  become: true
  tasks:
    - name: Wait for local registry to be listening on 5000
      wait_for:
        host: 127.0.0.1
        port: 5000
        timeout: 30

    - name: Ensure image is pulled on monitoring node (source quay or podman alias) with retries
      command: podman pull quay.io/podman/stable:latest
      register: pull_result
      retries: 3
      delay: 5
      until: pull_result.rc == 0 or "already exists" in pull_result.stdout

    - name: Tag pulled image for local registry
      command: podman tag quay.io/podman/stable:latest 192.168.4.63:5000/podman-system-metrics:latest
      changed_when: false

    - name: Push image to local registry (no TLS) with retries
      command: podman push --tls-verify=false 192.168.4.63:5000/podman-system-metrics:latest
      register: push_result
      retries: 3
      delay: 5
      until: push_result.rc == 0

- name: Distribute insecure registry configuration to all nodes
  hosts: all
  become: true
  tasks:
    - name: Ensure registries drop-in for local registry exists
      copy:
        dest: /etc/containers/registries.conf.d/local-registry.conf
        content: |
          unqualified-search-registries = ["docker.io"]

          [[registry]]
          prefix = "192.168.4.63:5000"
          location = "192.168.4.63:5000"
          insecure = true
        owner: root
        group: root
        mode: '0644'
