---
# Remove all Podman containers and optional images on target hosts.
# This playbook is intentionally guarded: set `confirm=true` when running to proceed.
# Example: ansible-playbook -i ansible/inventory.txt ansible/plays/monitoring/remove_all_podman.yaml -e confirm=true -e remove_images=true
- name: Remove all Podman containers from target hosts
  hosts: all
  become: true
  vars:
    confirm: false
    remove_images: false

  pre_tasks:
    - name: Abort if not explicitly confirmed
      fail:
        msg: "This playbook will stop and remove ALL Podman containers on the target hosts. Rerun with -e confirm=true to proceed."
      when: not confirm | bool

  tasks:
    - name: List all Podman containers (IDs)
      command: podman ps -aq
      register: podman_all
      changed_when: false
      failed_when: false

    - name: Stop all Podman containers
      command: podman stop {{ podman_all.stdout_lines | join(' ') }}
      when: podman_all.stdout != ''
      failed_when: false

    - name: Remove all Podman containers
      command: podman rm -f {{ podman_all.stdout_lines | join(' ') }}
      when: podman_all.stdout != ''
      failed_when: false

    - name: Find Podman-related systemd units (if present)
      command: systemctl list-units --type=service --state=loaded
      register: systemd_units
      changed_when: false
      failed_when: false

    - name: Extract Podman unit names
      set_fact:
        podman_units: "{{ systemd_units.stdout_lines | select('search','podman') | map('split') | map('first') | list }}"

    - name: Stop and disable Podman unit(s)
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop: "{{ podman_units }}"
      when: podman_units is defined and podman_units | length > 0
      failed_when: false

    - name: Optionally remove all Podman images (prune)
      command: podman image prune -a -f
      when: remove_images | bool
      failed_when: false

    - name: Show summary
      debug:
        msg: |
          podman_containers_removed: "{{ podman_all.stdout_lines | default([]) }}"
          podman_units_disabled: "{{ podman_units | default([]) }}"
          images_pruned: "{{ remove_images | bool }}"
