---
# HostPath PersistentVolume for Syslog Server (infrastructure component)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: syslog-pv
  labels:
    app: syslog-server
    vmstation.io/component: logging
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /srv/monitoring_data/syslog
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
  claimRef:
    namespace: infrastructure
    name: syslog-data-syslog-server-0
