---
# VMStation Site Playbook - Main orchestrator
# This imports modular subsites in recommended order, but operators should prefer
# running subsites individually for safer, more controlled deployments.
#
# Recommended individual execution order:
# 1. ansible-playbook -i ansible/inventory.txt ansible/subsites/01-checks.yaml
# 2. ansible-playbook -i ansible/inventory.txt ansible/subsites/02-certs.yaml  
# 3. ansible-playbook -i ansible/inventory.txt ansible/subsites/03-monitoring.yaml
# 4. ansible-playbook -i ansible/inventory.txt ansible/plays/kubernetes_stack.yaml
# 5. ansible-playbook -i ansible/inventory.txt ansible/plays/kubernetes/jellyfin-minimal.yml

# === Modular Subsites (Safe, Check-Only Operations) ===
- import_playbook: subsites/01-checks.yaml
- import_playbook: subsites/02-certs.yaml  
- import_playbook: subsites/03-monitoring.yaml

# === Core Infrastructure Deployment ===
- import_playbook: plays/kubernetes_stack.yaml

# === Application Services ===
- import_playbook: plays/jellyfin.yml
  when: jellyfin_enabled | default(true)

# === Final Validation ===
- name: "VMStation Deployment Validation"
  hosts: all
  gather_facts: false
  become: false
  vars:
    ansible_connection: local
  tags: [validate]
  tasks:
    - name: "Validate Jellyfin deployment if enabled"
      include_role:
        name: ../roles/jellyfin
        tasks_from: main
      when: jellyfin_enabled | default(true)
      tags: [jellyfin, validate]

    - name: "Generate deployment summary"
      ansible.builtin.debug:
        msg:
          - "=== VMStation Deployment Summary ==="
          - "Jellyfin Pod Ready: {{ jellyfin_pod_ready | default('N/A') }}"
          - "Jellyfin Service NodePort: {{ jellyfin_service_nodeport | default('N/A') }}"
          - "ServiceMonitor Present: {{ servicemonitor_present | default('N/A') }}"
          - "Prometheus Target Found: {{ prometheus_target_found | default('N/A') }}"
          - ""
          - "{% if jellyfin_enabled | default(true) %}Access Jellyfin at: http://{{ jellyfin_node_name | default('storagenodet3500') }}:{{ jellyfin_service_nodeport | default('30096') }}{% else %}Jellyfin deployment is disabled{% endif %}"
          - ""
          - "{% if servicemonitor_present == true %}To check Prometheus targets: kubectl port-forward -n monitoring svc/prometheus-kube-prometheus-prometheus 9090:9090{% endif %}"
          - "{% if servicemonitor_present == 'skip' %}ServiceMonitor creation skipped - Prometheus Operator not detected{% endif %}"
      tags: [validate]

    - name: "Fail deployment if Jellyfin pod is not ready"
      ansible.builtin.fail:
        msg: "Jellyfin deployment failed - pod not ready within timeout"
      when: 
        - jellyfin_enabled | default(true)
        - not (jellyfin_pod_ready | default(false))
      tags: [validate]