---
# VMStation Site Playbook - Main orchestrator
# This imports modular subsites in recommended order, but operators should prefer
# running subsites individually for safer, more controlled deployments.
#
# Recommended individual execution order:
# 1. ansible-playbook -i ansible/inventory.txt ansible/subsites/01-checks.yaml
# 2. ansible-playbook -i ansible/inventory.txt ansible/subsites/02-certs.yaml  
# 3. ansible-playbook -i ansible/inventory.txt ansible/subsites/03-monitoring.yaml
# 4. ansible-playbook -i ansible/inventory.txt ansible/subsites/04-jellyfin.yaml
# 4. ansible-playbook -i ansible/inventory.txt ansible/subsites/05-extra_apps.yaml
# 5. ansible-playbook -i ansible/inventory.txt ansible/plays/kubernetes_stack.yaml
# 6. ansible-playbook -i ansible/inventory.txt ansible/plays/jellyfin.yml

# === Modular Subsites (Safe, Check-Only Operations) ===
- import_playbook: subsites/01-checks.yaml
# - import_playbook: subsites/02-certs.yaml  
- import_playbook: subsites/03-monitoring.yaml
# - import_playbook: subsites/04-jellyfin.yaml
- import_playbook: subsites/05-extra_apps.yaml

# === Core Infrastructure Deployment ===
- import_playbook: plays/kubernetes_stack.yaml

# === Application Services ===
- import_playbook: plays/jellyfin.yml
  when: jellyfin_enabled | default(true)

# === Final Validation ===
- name: "VMStation Deployment Validation"
  hosts: all
  gather_facts: false
  become: false
  tags: [validate]
  vars:
    apps_to_check:
      - name: "kubernetes-dashboard"
        namespace: "kubernetes-dashboard"
        label_selector: "app=kubernetes-dashboard"
        service: "kubernetes-dashboard"
      - name: "drone"
        namespace: "drone"
        label_selector: "app=drone"
        service: "drone"
      - name: "mongodb"
        namespace: "mongodb"
        label_selector: "app=mongodb"
        service: "mongodb"

  tasks:
    - name: "Gather pod listings for extra apps"
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: "{{ item.namespace }}"
        label_selectors: "{{ item.label_selector }}"
      loop: "{{ apps_to_check }}"
      register: pod_checks
      failed_when: false

    - name: "Gather Service info for extra apps"
      kubernetes.core.k8s_info:
        kind: Service
        namespace: "{{ item.namespace }}"
        name: "{{ item.service }}"
      loop: "{{ apps_to_check }}"
      register: svc_checks
      failed_when: false

    - name: "Build list of failing apps (no ready pods)"
      set_fact:
        failing_apps: "{{ failing_apps | default([]) + [ apps_to_check[item_index].name ] }}"
      loop: "{{ pod_checks.results }}"
      loop_control:
        index_var: item_index
      when: >-
        (item.resources | default([]) | length) == 0
        or ((item.resources | default([]) | json_query("[?status.conditions[?(@.type=='Ready' && @.status=='True')]]") | length) == 0)

    - name: "Print concise status for each extra app"
      ansible.builtin.debug:
        msg: >-
          {{ apps_to_check[idx].name }}: pods={{ (item.resources | default([]) | length) }}
          ready={{ (item.resources | default([]) | json_query("[?status.conditions[?(@.type=='Ready' && @.status=='True')]]") | length) }}
          svc={{ (svc_checks.results[idx].resources | default([]) | length > 0) if (svc_checks is defined and svc_checks.results is defined and (svc_checks.results | length) > idx) else false }}
          nodePort={{ (svc_checks.results[idx].resources[0].spec.ports[0].nodePort) if (svc_checks is defined and svc_checks.results is defined and (svc_checks.results | length) > idx and (svc_checks.results[idx].resources | default([]) | length) > 0) else 'N/A' }}
      loop: "{{ pod_checks.results }}"
      loop_control:
        index_var: idx

    - name: "Fail if any extra app has no ready pods"
      ansible.builtin.fail:
        msg: "One or more required extra-app pods are not ready: {{ failing_apps | default([]) | join(', ') }}"
      when: failing_apps is defined and (failing_apps | length) > 0

    - name: "Optional: Validate Jellyfin using existing role (if enabled)"
      include_role:
        name: ../roles/jellyfin
        tasks_from: main
      when: jellyfin_enabled | default(true)
      tags: [jellyfin, validate]

    - name: "Deployment summary"
      ansible.builtin.debug:
        msg: >-
          VMStation validation completed. Extra apps failing: {{ failing_apps | default([]) | join(', ') or 'none' }}