apiVersion: v1
kind: Service
metadata:
  name: cups-nodeport
  namespace: printer-ops
spec:
  type: NodePort
  selector:
    app: cups-avahi
  ports:
  - name: ipp
    protocol: TCP
    port: 631
    targetPort: 631
    nodePort: 30031
  - name: raw9100
    protocol: TCP
    port: 9100
    targetPort: 9100
    nodePort: 30032
