apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
data:
  Corefile: |
    # VMStation homelab.com domain configuration
    homelab.com:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        # Static host mappings for homelab.com subdomains
        hosts {
            192.168.4.61 jellyfin.homelab.com storage.homelab.com
            192.168.4.62 compute.homelab.com
            192.168.4.63 grafana.homelab.com control.homelab.com
            # Fallback for any other homelab.com subdomain
            fallthrough
        }
        prometheus :9153
        cache 30
        loop
        reload
        loadbalance
    }
    
    # Default Kubernetes cluster configuration
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        prometheus :9153
        forward . 8.8.8.8 1.1.1.1 {
            max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }