---
# ansible/roles/rke2/tasks/preflight.yml
# Pre-flight checks before RKE2 installation

- name: Check if running on RHEL
  assert:
    that:
      - ansible_os_family == "RedHat"
    fail_msg: "This role is designed for RHEL-based systems"
    success_msg: "Running on RHEL-based system"

- name: Check RHEL version
  debug:
    msg: "Detected RHEL {{ ansible_distribution_version }}"

- name: Check if RKE2 is already installed
  stat:
    path: /usr/local/bin/rke2
  register: rke2_binary_exists

- name: Check if RKE2 server is running
  systemd:
    name: rke2-server
  register: rke2_service_status
  ignore_errors: true

- name: Display RKE2 installation status
  debug:
    msg: "RKE2 already installed: {{ rke2_binary_exists.stat.exists }}, Service running: {{ rke2_service_status.status.ActiveState | default('unknown') }}"
  when: rke2_binary_exists.stat.exists

- name: Check available disk space
  shell: df -h {{ rke2_data_dir | dirname }} | tail -1 | awk '{print $4}'
  register: available_space
  changed_when: false

- name: Display available disk space
  debug:
    msg: "Available disk space for RKE2 data: {{ available_space.stdout }}"

- name: Check available memory
  debug:
    msg: "Available memory: {{ ansible_memory_mb.real.free }}MB / {{ ansible_memory_mb.real.total }}MB"

- name: Warn if low memory
  debug:
    msg: "WARNING: Low memory detected. RKE2 requires at least 2GB RAM."
  when: ansible_memory_mb.real.total < 2048

- name: Check for conflicting Kubernetes installations
  stat:
    path: "{{ item }}"
  register: k8s_artifacts
  loop:
    - /etc/kubernetes
    - /var/lib/kubelet
    - /usr/local/bin/kubelet
    - /usr/bin/kubelet
  
- name: Display conflicting artifacts warning
  debug:
    msg: "WARNING: Found existing Kubernetes artifacts. Run cleanup script first: scripts/cleanup-homelab-k8s-artifacts.sh"
  when: k8s_artifacts.results | selectattr('stat.exists', 'equalto', true) | list | length > 0

- name: Fail if conflicting Kubernetes installations exist
  fail:
    msg: |
      Existing Kubernetes installation detected. Please run the cleanup script first:
      
      On homelab node (192.168.4.62):
        sudo /srv/monitoring_data/VMStation/scripts/cleanup-homelab-k8s-artifacts.sh
      
      Or via Ansible:
        ansible-playbook -i ansible/inventory/hosts.yml ansible/playbooks/cleanup-homelab.yml
      
      Then re-run this playbook.
  when: 
    - k8s_artifacts.results | selectattr('stat.exists', 'equalto', true) | list | length > 0
    - not (rke2_binary_exists.stat.exists | default(false))
