---
# ansible/roles/rke2/tasks/service.yml
# RKE2 service management tasks

- name: Check if rke2-server.service exists
  stat:
    path: /etc/systemd/system/rke2-server.service
  register: rke2_service_file

- name: Check if rke2-server.service exists in /usr/lib
  stat:
    path: /usr/lib/systemd/system/rke2-server.service
  register: rke2_service_file_usr
  when: not rke2_service_file.stat.exists

- name: Display service file location
  debug:
    msg: "RKE2 service file found: {{ rke2_service_file.stat.path if rke2_service_file.stat.exists else (rke2_service_file_usr.stat.path if rke2_service_file_usr.stat.exists else 'Not found') }}"

- name: Enable rke2-server service
  systemd:
    name: rke2-server
    enabled: yes
    daemon_reload: yes
  become: true

- name: Start rke2-server service
  systemd:
    name: rke2-server
    state: started
  become: true
  register: rke2_service_start

- name: Wait for rke2-server to be active
  systemd:
    name: rke2-server
  register: rke2_service_status
  until: rke2_service_status.status.ActiveState == "active"
  retries: 30
  delay: 10
  become: true

- name: Display rke2-server service status
  debug:
    msg: "RKE2 server service is {{ rke2_service_status.status.ActiveState }}"

- name: Check rke2-server service logs
  command: journalctl -u rke2-server -n 50 --no-pager
  register: rke2_service_logs
  changed_when: false
  become: true

- name: Display recent rke2-server logs
  debug:
    msg: "{{ rke2_service_logs.stdout_lines[-20:] }}"
